const newLine = "<br>";
const CMD = {
    "Tx":{
        "num":0,
        "description":""
    },
    "TxSize":{
        "num":1,
        "description":""
    },
    "Alpha":{
        "num":2,
        "description":""
    },
    "End":{
        "num":3,
        "description":""
    },
    "Pos":{
        "num":4,
        "description":""
    },
    "ColorALL":{
        "num":5,
        "description":""
    },
    "Move":{
        "num":6,
        "description":""
    },
    "STAGE_BGM":{
        "num":7,
        "description":""
    },
    "SetFlat3D":{
        "num":8,
        "description":""
    },
    "ChangeFlat3D":{
        "num":9,
        "description":""
    },
    "SetCamDir":{
        "num":10,
        "description":""
    },
    "DisCamDir":{
        "num":11,
        "description":""
    },
    "Set3DObj":{
        "num":12,
        "description":""
    },
    "SetWAngleX":{
        "num":13,
        "description":""
    },
    "SetWAngleY":{
        "num":14,
        "description":""
    },
    "SetWAngleZ":{
        "num":15,
        "description":""
    },
    "SetLAngleX":{
        "num":16,
        "description":""
    },
    "SetLAngleY":{
        "num":17,
        "description":""
    },
    "SetLAngleZ":{
        "num":18,
        "description":""
    },
    "SetBoneWAngleX":{
        "num":19,
        "description":""
    },
    "SetBoneWAngleY":{
        "num":20,
        "description":""
    },
    "SetBoneWAngleZ":{
        "num":21,
        "description":""
    },
    "SetBoneLAngleX":{
        "num":22,
        "description":""
    },
    "SetBoneLAngleY":{
        "num":23,
        "description":""
    },
    "SetBoneLAngleZ":{
        "num":24,
        "description":""
    },
    "ShowMesh":{
        "num":25,
        "description":""
    },
    "HideMesh":{
        "num":26,
        "description":""
    },
    "PlayAnime":{
        "num":27,
        "description":""
    },
    "Length_End":{
        "num":28,
        "description":""
    },
    "SetScall":{
        "num":29,
        "description":""
    },
    "RACE_START":{
        "num":30,
        "description":"バトルを始める"
    },
    "RACE_END":{
        "num":31,
        "description":"バトルが終わる"
    },
    "FADE_STAGE_BGM":{
        "num":32,
        "description":""
    },
    "CHANGE_SCENE":{
        "num":33,
        "description":"シーンを変える（メニューや漫画などの）" + newLine + "LSのH7001のみ引数「100」を使う"
    },
    "LPos":{
        "num":34,
        "description":""
    },
    "LMove":{
        "num":35,
        "description":""
    },
    "LLoopX":{
        "num":36,
        "description":""
    },
    "LLoopY":{
        "num":37,
        "description":""
    },
    "LLoopZ":{
        "num":38,
        "description":""
    },
    "Angle":{
        "num":39,
        "description":""
    },
    "AngleLoop":{
        "num":40,
        "description":""
    },
    "Move2":{
        "num":41,
        "description":""
    },
    "PosX":{
        "num":42,
        "description":""
    },
    "PosY":{
        "num":43,
        "description":""
    },
    "PosZ":{
        "num":44,
        "description":""
    },
    "PlaySE":{
        "num":45,
        "description":""
    },
    "SET_MT_NONE":{
        "num":46,
        "description":""
    },
    "SetCamPos":{
        "num":47,
        "description":""
    },
    "SetCamTarget":{
        "num":48,
        "description":""
    },
    "CamMoveWait":{
        "num":49,
        "description":""
    },
    "SetComic":{
        "num":50,
        "description":"引数１：コマの番号" + newLine + "引数２：スクリプト内のイメージ番号"
    },
    "ComicPos":{
        "num":51,
        "description":"引数１：コマの番号" + newLine + "引数２：x座標" + newLine + "引数３：y座標" + newLine + "引数４：アニメ時間（フレーム）" + newLine + "引数５：アニメ効果の種類"
    },
    "ComicAlpha":{
        "num":52,
        "description":"引数１：コマの番号" + newLine + "引数２：from Alpha"  + newLine + "引数３：to Alpha" + newLine + "引数４：アニメ時間（フレーム）" + newLine + "引数５：アニメ効果の種類"
    },
    "ComicWait":{
        "num":53,
        "description":"引数１：コマの番号" + newLine + "引数２：不明（SSでは使わない）"
    },
    "Scene_to_Comic":{
        "num":54,
        "description":"引数１：コマの番号" + newLine + "引数２：width" + newLine + "引数３：height"
    },
    "SKY_DOME":{
        "num":55,
        "description":""
    },
    "Fill_BG":{
        "num":56,
        "description":""
    },
    "ComicEnd":{
        "num":57,
        "description":""
    },
    "CamComtroll":{
        "num":58,
        "description":""
    },
    "ComicSceneStop":{
        "num":59,
        "description":""
    },
    "BtnWait":{
        "num":60,
        "description":""
    },
    "EyeMove":{
        "num":61,
        "description":""
    },
    "SetZoom":{
        "num":62,
        "description":""
    },
    "BG_Alpha":{
        "num":63,
        "description":""
    },
    "BG_Wait":{
        "num":64,
        "description":""
    },
    "StartCount":{
        "num":65,
        "description":""
    },
    "WaitMoveEye":{
        "num":66,
        "description":""
    },
    "WaitFrame":{
        "num":67,
        "description":""
    },
    "FTV_Play":{
        "num":68,
        "description":""
    },
    "FTV_Wait":{
        "num":69,
        "description":""
    },
    "HideMsgWnd":{
        "num":70,
        "description":""
    },
    "FTV_End":{
        "num":71,
        "description":""
    },
    "SkipEventPoint":{
        "num":72,
        "description":""
    },
    "SkipEventFlg":{
        "num":73,
        "description":""
    },
    "PlayComicSE":{
        "num":74,
        "description":""
    },
    "StopComicSE":{
        "num":75,
        "description":""
    },
    "PlayComicBGM":{
        "num":76,
        "description":""
    },
    "StopComicBGM":{
        "num":77,
        "description":""
    },
    "VolComicBGM":{
        "num":78,
        "description":""
    },
    "HideALLComic":{
        "num":79,
        "description":""
    },
    "Stage_BGM_Vol":{
        "num":80,
        "description":""
    },
    "SET_CPU_FLG":{
        "num":81,
        "description":""
    },
    "SET_CPU_MODE":{
        "num":82,
        "description":""
    },
    "CHK_LENGTH":{
        "num":83,
        "description":""
    },
    "END_CHK_LENGTH":{
        "num":84,
        "description":""
    },
    "CHK_POSTION":{
        "num":85,
        "description":""
    },
    "END_CHK_POSTION":{
        "num":86,
        "description":""
    },
    "WAIT_MOTION":{
        "num":87,
        "description":""
    },
    "END_WAIT_MOTION":{
        "num":88,
        "description":""
    },
    "CHANGE_SPEED":{
        "num":89,
        "description":""
    },
    "CHANGE_CAM_TYPE":{
        "num":90,
        "description":""
    },
    "Set2P":{
        "num":91,
        "description":""
    },
    "CharChk_and_Tx":{
        "num":92,
        "description":""
    },
    "ChangeR":{
        "num":93,
        "description":""
    },
    "ChangeG":{
        "num":94,
        "description":""
    },
    "ChangeB":{
        "num":95,
        "description":""
    },
    "ChangeColor":{
        "num":96,
        "description":""
    },
    "SetGray":{
        "num":97,
        "description":""
    },
    "MoveX":{
        "num":98,
        "description":""
    },
    "MoveY":{
        "num":99,
        "description":""
    },
    "MoveZ":{
        "num":100,
        "description":""
    },
    "SetUV_X":{
        "num":101,
        "description":""
    },
    "RePlay":{
        "num":102,
        "description":""
    },
    "IsStart":{
        "num":103,
        "description":""
    },
    "ShowGoal":{
        "num":104,
        "description":""
    },
    "CHK_WIN_TRAIN":{
        "num":105,
        "description":""
    },
    "END_CHK_WINTRAIN":{
        "num":106,
        "description":""
    },
    "N_ADD_OBJ":{
        "num":107,
        "description":""
    },
    "N_POS":{
        "num":108,
        "description":""
    },
    "START_TIME_LINE":{
        "num":109,
        "description":""
    },
    "N_MOVE":{
        "num":110,
        "description":""
    },
    "WAIT_TIME_LINE":{
        "num":111,
        "description":""
    },
    "N_DEL_OBJ":{
        "num":112,
        "description":""
    },
    "SCREEN_FADE":{
        "num":113,
        "description":""
    },
    "N_CHANGE_ANIME":{
        "num":114,
        "description":""
    },
    "TRAIN_SPEED":{
        "num":115,
        "description":""
    },
    "TRAIN_FLG":{
        "num":116,
        "description":""
    },
    "SCENE_LIGHT":{
        "num":117,
        "description":""
    },
    "CHANGE_CAM_LENGTH":{
        "num":118,
        "description":""
    },
    "CHANGE_CAM_DIRX":{
        "num":119,
        "description":""
    },
    "CHANGE_CAM_DIRY":{
        "num":120,
        "description":""
    },
    "CHANGE_CAM_DIRZ":{
        "num":121,
        "description":""
    },
    "R_Drift":{
        "num":122,
        "description":""
    },
    "L_Drift":{
        "num":123,
        "description":""
    },
    "IS_TRAIN_HIT":{
        "num":124,
        "description":""
    },
    "TO_RAIL":{
        "num":125,
        "description":""
    },
    "SLEEP_TRAIN":{
        "num":126,
        "description":""
    },
    "RandWAngle":{
        "num":127,
        "description":""
    },
    "RandMove":{
        "num":128,
        "description":""
    },
    "ADD_OBJ":{
        "num":129,
        "description":""
    },
    "START_COMIC":{
        "num":130,
        "description":""
    },
    "SetRand3DObj":{
        "num":131,
        "description":""
    },
    "Offset3DObj":{
        "num":132,
        "description":""
    },
    "RandPos":{
        "num":133,
        "description":""
    },
    "RandPlaySE":{
        "num":134,
        "description":""
    },
    "RandAngleX":{
        "num":135,
        "description":""
    },
    "RandAngleY":{
        "num":136,
        "description":""
    },
    "RandAngleZ":{
        "num":137,
        "description":""
    },
    "CHK_TRAIN_STATE":{
        "num":138,
        "description":""
    },
    "END_CHK_TRAIN_STATE":{
        "num":139,
        "description":""
    },
    "CHK_TRAIN_SPEED_U":{
        "num":140,
        "description":""
    },
    "CHK_TRAIN_SPEED_D":{
        "num":141,
        "description":""
    },
    "END_CHK_TRAIN_SPEED_U":{
        "num":142,
        "description":""
    },
    "END_CHK_TRAIN_SPEED_D":{
        "num":143,
        "description":""
    },
    "ChkStory_and_Tx":{
        "num":144,
        "description":""
    },
    "ClearStory_and_Tx":{
        "num":145,
        "description":""
    },
    "N_L_ANGLE_X":{
        "num":146,
        "description":""
    },
    "N_L_ANGLE_Y":{
        "num":147,
        "description":""
    },
    "N_L_ANGLE_Z":{
        "num":148,
        "description":""
    },
    "Comic_Glay":{
        "num":149,
        "description":""
    },
    "N_MoveMesh_X":{
        "num":150,
        "description":""
    },
    "N_MoveMesh_Y":{
        "num":151,
        "description":""
    },
    "N_MoveMesh_Z":{
        "num":152,
        "description":""
    },
    "SetComic_Blur":{
        "num":153,
        "description":""
    },
    "SetComic_Blur_Speed":{
        "num":154,
        "description":""
    },
    "TRACK_BOMB":{
        "num":155,
        "description":""
    },
    "Hide_Sky_Doom":{
        "num":156,
        "description":""
    },
    "ADD_POINT":{
        "num":157,
        "description":""
    },
    "CHK_POINT":{
        "num":158,
        "description":""
    },
    "ELSE_CHK_POINT":{
        "num":159,
        "description":""
    },
    "ELSE_IF_CHK_POINT":{
        "num":160,
        "description":""
    },
    "END_CHK_POINT":{
        "num":161,
        "description":""
    },
    "GOTO_SCRIPT":{
        "num":162,
        "description":""
    },
    "SHEAK_COMIC":{
        "num":163,
        "description":""
    },
    "STORY_OPEN":{
        "num":164,
        "description":""
    },
    "STORY_CLEAR":{
        "num":165,
        "description":""
    },
    "CHAR_OPEN":{
        "num":166,
        "description":""
    },
    "SAVE_GAME":{
        "num":167,
        "description":""
    },
    "KEISUKE_COUNT":{
        "num":168,
        "description":""
    },
    "RandPlayComicSE":{
        "num":169,
        "description":""
    },
    "TITLE_MODE":{
        "num":170,
        "description":""
    },
    "GOING":{
        "num":171,
        "description":""
    },
    "RAND_IF":{
        "num":172,
        "description":""
    },
    "ELSE_RAND_IF":{
        "num":173,
        "description":""
    },
    "END_RAND_IF":{
        "num":174,
        "description":""
    },
    "CHK_SP_BREAK":{
        "num":175,
        "description":""
    },
    "END_CHK_SP_BREAK":{
        "num":176,
        "description":""
    },
    "CHK_DRIFT":{
        "num":177,
        "description":""
    },
    "END_CHK_DRIFT":{
        "num":178,
        "description":""
    },
    "ENDING_MODE":{
        "num":179,
        "description":""
    },
    "ChkCause_and_Tx":{
        "num":180,
        "description":""
    },
    "SET_DRAW_TYPE":{
        "num":181,
        "description":""
    },
    "To_TxSize":{
        "num":182,
        "description":""
    },
    "OPEN_CAUSE":{
        "num":183,
        "description":""
    },
    "DIS_TRAIN_SPEED":{
        "num":184,
        "description":""
    },
    "CHK_RACE_TIME":{
        "num":185,
        "description":""
    },
    "END_CHK_RACE_TIME":{
        "num":186,
        "description":""
    },
    "End_Comic":{
        "num":187,
        "description":""
    },
    "WAIT_RAIL":{
        "num":188,
        "description":""
    },
    "END_WAIT_RAIL":{
        "num":189,
        "description":""
    },
    "COMIC_SCALE":{
        "num":190,
        "description":""
    },
    "USO_COUNT":{
        "num":191,
        "description":""
    },
    "WaitRandPlaySE":{
        "num":192,
        "description":""
    },
    "FROM":{
        "num":193,
        "description":""
    },
    "GOTO":{
        "num":194,
        "description":""
    },
    "CHK_TRAIN_TYPE":{
        "num":195,
        "description":""
    },
    "RAND_IF_AVG":{
        "num":196,
        "description":""
    },
    "CHK_NOTCH":{
        "num":197,
        "description":""
    },
    "WAIT_RAIL_ONLY":{
        "num":198,
        "description":""
    },
    "ONE_TRACK_DRIFT":{
        "num":199,
        "description":""
    },
    "LAST_STATION":{
        "num":200,
        "description":""
    },
    "OSSAN":{
        "num":201,
        "description":""
    },
    "SET_TAIL_SCALE":{
        "num":202,
        "description":""
    },
    "OPEN_HUTA":{
        "num":203,
        "description":""
    },
    "SET_GN":{
        "num":204,
        "description":""
    },
    "MDL_GETINDEX":{
        "num":205,
        "description":""
    },
    "INDEX_BONE_ROT_X":{
        "num":206,
        "description":""
    },
    "INDEX_BONE_ROT_Y":{
        "num":207,
        "description":""
    },
    "INDEX_BONE_ROT_Z":{
        "num":208,
        "description":""
    },
    "INDEX_BONE_L_ROT_X":{
        "num":209,
        "description":""
    },
    "INDEX_BONE_L_ROT_Y":{
        "num":210,
        "description":""
    },
    "INDEX_BONE_L_ROT_Z":{
        "num":211,
        "description":""
    },
    "CREATE_INDEX":{
        "num":212,
        "description":""
    },
    "IB_LI_CREATE_ROT_X":{
        "num":213,
        "description":""
    },
    "IB_LI_CREATE_ROT_Y":{
        "num":214,
        "description":""
    },
    "IB_LI_CREATE_ROT_Z":{
        "num":215,
        "description":""
    },
    "IB_LI_SET_ROT_X":{
        "num":216,
        "description":""
    },
    "IB_LI_SET_ROT_Y":{
        "num":217,
        "description":""
    },
    "IB_LI_SET_ROT_Z":{
        "num":218,
        "description":""
    },
    "IB_LI_SET_LOOP_X":{
        "num":219,
        "description":""
    },
    "IB_LI_SET_LOOP_Y":{
        "num":220,
        "description":""
    },
    "IB_LI_SET_LOOP_Z":{
        "num":221,
        "description":""
    },
    "ADD_MY_OBJ":{
        "num":222,
        "description":""
    },
    "INDEX_BONE_L_POS_X":{
        "num":223,
        "description":""
    },
    "INDEX_BONE_L_POS_Y":{
        "num":224,
        "description":""
    },
    "INDEX_BONE_L_POS_Z":{
        "num":225,
        "description":""
    },
    "IB_LI_CREATE_L_POS_X":{
        "num":226,
        "description":""
    },
    "IB_LI_CREATE_L_POS_Y":{
        "num":227,
        "description":""
    },
    "IB_LI_CREATE_L_POS_Z":{
        "num":228,
        "description":""
    },
    "IB_LI_SET_L_POS_X":{
        "num":229,
        "description":""
    },
    "IB_LI_SET_L_POS_Y":{
        "num":230,
        "description":""
    },
    "IB_LI_SET_L_POS_Z":{
        "num":231,
        "description":""
    },
    "FROM_ADDMT":{
        "num":232,
        "description":""
    },
    "MOVE_UV_X":{
        "num":233,
        "description":""
    },
    "MOVE_UV_Y":{
        "num":234,
        "description":""
    },
    "CREATE_UV_MOVE_X":{
        "num":235,
        "description":""
    },
    "IB_LI_SET_LOOP_LPOSX":{
        "num":236,
        "description":""
    },
    "IB_LI_SET_LOOP_LPOSY":{
        "num":237,
        "description":""
    },
    "IB_LI_SET_LOOP_LPOSZ":{
        "num":238,
        "description":""
    },
    "RELEASE_ALL_IB_LIST":{
        "num":239,
        "description":""
    },
    "ADD_MY_OBJ_INDEX":{
        "num":240,
        "description":""
    },
    "TO_TAGET_POS":{
        "num":241,
        "description":""
    },
    "ATK_HIT":{
        "num":242,
        "description":""
    },
    "ATK_END":{
        "num":243,
        "description":""
    },
    "SET_RELEASE_PARAM":{
        "num":244,
        "description":""
    },
    "CREATE_LENSFLEAR":{
        "num":245,
        "description":""
    },
    "SET_LENSFLEAR_PARAM":{
        "num":246,
        "description":""
    },
    "SET_LENSFLEAR_MT":{
        "num":247,
        "description":""
    },
    "RAIL_POS_TO_BUFF":{
        "num":248,
        "description":""
    },
    "BUFF_TO_CAM_POS":{
        "num":249,
        "description":""
    },
    "BUFF_TO_TARGET_POS":{
        "num":250,
        "description":""
    },
    "FTV_BASE_PROC":{
        "num":251,
        "description":""
    },
    "FTV_NEXT_PROC":{
        "num":252,
        "description":""
    },
    "MDL_INDEX_TO_VIEW":{
        "num":253,
        "description":""
    },
    "SET_FOG_LENGTH":{
        "num":254,
        "description":""
    },
    "SET_UV_MOVE_X":{
        "num":255,
        "description":""
    },
    "SET_UV_LOOP_X":{
        "num":256,
        "description":""
    },
    "CREATE_MESH_INDEX":{
        "num":257,
        "description":""
    },
    "SET_MESH_INDEX":{
        "num":258,
        "description":""
    },
    "INDEX_BONE_L_ADD_ROT_X":{
        "num":259,
        "description":""
    },
    "INDEX_BONE_L_ADD_ROT_Y":{
        "num":260,
        "description":""
    },
    "INDEX_BONE_L_ADD_ROT_Z":{
        "num":261,
        "description":""
    },
    "CHANGE_SCALL":{
        "num":262,
        "description":""
    },
    "CHK_CLEAR_STORY":{
        "num":263,
        "description":""
    },
    "CHK_OPEN_STORY":{
        "num":264,
        "description":""
    },
    "SET_LENSFLEAR_ALL_FLG":{
        "num":265,
        "description":""
    },
    "CHK_USE_CHAR":{
        "num":266,
        "description":""
    },
    "SET_OBJ_FOG_NO":{
        "num":267,
        "description":""
    },
    "SET_OBJ_RENDER_ID":{
        "num":268,
        "description":""
    },
    "PLAY_STAGE_BGM":{
        "num":269,
        "description":""
    },
    "CHANGE_TRAIN_FOG":{
        "num":270,
        "description":""
    },
    "FIRST_OBJ_SET_ANIME":{
        "num":271,
        "description":""
    },
    "SET_CAMPOINT_2P2C":{
        "num":272,
        "description":""
    },
    "SET_CAMPOINT_1P2C":{
        "num":273,
        "description":""
    },
    "CAM_POINT_PER":{
        "num":274,
        "description":""
    },
    "CAM_TARGET_PER":{
        "num":275,
        "description":""
    },
    "SET_CAM_POINT_LENGTH":{
        "num":276,
        "description":""
    },
    "SET_CAM_OFFSET":{
        "num":277,
        "description":""
    },
    "START_WIPER":{
        "num":278,
        "description":""
    },
    "CREATE_TRAIN_ORG":{
        "num":279,
        "description":""
    },
    "ORG_SET_RAIL":{
        "num":280,
        "description":""
    },
    "ORG_ADD":{
        "num":281,
        "description":""
    },
    "SET_CAMPOINT_K":{
        "num":282,
        "description":""
    },
    "ORG_SET_POS":{
        "num":283,
        "description":""
    },
    "ORG_SET_FOG":{
        "num":284,
        "description":""
    },
    "ORG_RELEASE":{
        "num":285,
        "description":""
    },
    "PLAY_FTV_END":{
        "num":286,
        "description":""
    },
    "CNG_TRAIN_MAT_COL":{
        "num":287,
        "description":""
    },
    "CNG_ORG_MAT_COL":{
        "num":288,
        "description":""
    },
    "IS_CAUTION":{
        "num":289,
        "description":""
    },
    "ENDWAIT_COMIC":{
        "num":290,
        "description":""
    },
    "SET_COMIC_BG_COLOR":{
        "num":291,
        "description":""
    },
    "TX_2_TRAIN":{
        "num":292,
        "description":""
    },
    "CHANGE_MT_COL_TRAIN":{
        "num":293,
        "description":""
    },
    "CNG_MT_COL":{
        "num":294,
        "description":""
    },
    "RETURN":{
        "num":295,
        "description":""
    },
    "ReLoadSE":{
        "num":296,
        "description":""
    },
    "BASE_POINT_CAM":{
        "num":297,
        "description":""
    },
    "STOP_3D":{
        "num":298,
        "description":""
    },
    "STOP_STAGE_BGM":{
        "num":299,
        "description":""
    },
    "TRAIN_UD":{
        "num":300,
        "description":""
    },
    "SET_CAM_TARGET_OFFSET":{
        "num":301,
        "description":""
    },
    "SET_CAM_POINT_1T_ROT":{
        "num":302,
        "description":""
    },
    "SET_CAM_T_LENGHT":{
        "num":303,
        "description":""
    },
    "SET_CAM_T_ROT_X":{
        "num":304,
        "description":""
    },
    "SET_CAM_T_ROT_Y":{
        "num":305,
        "description":""
    },
    "SET_CAM_T_OFFSET":{
        "num":306,
        "description":""
    },
    "NO_OUTRUN":{
        "num":307,
        "description":""
    },
    "SET_WHEEL_FIRE":{
        "num":308,
        "description":""
    },
    "RELOAD_OP_TRAIN":{
        "num":309,
        "description":""
    },
    "BackR_Drift":{
        "num":310,
        "description":""
    },
    "BackL_Drift":{
        "num":311,
        "description":""
    },
    "CHK_MOTION":{
        "num":312,
        "description":""
    },
    "ORG_SET_STYLE_POS":{
        "num":313,
        "description":""
    },
    "RECREATE_TRAIN":{
        "num":314,
        "description":""
    },
    "SET_CAMPOINT_1P2T":{
        "num":315,
        "description":""
    },
    "BUFF_TO_SC_CAM_POS":{
        "num":316,
        "description":""
    },
    "SC_ORG_MODE_CHANGE":{
        "num":317,
        "description":""
    },
    "SC_ORG_INIT_POS":{
        "num":318,
        "description":""
    },
    "SC_ORG_SET_POS":{
        "num":319,
        "description":""
    },
    "SC_ORG_SET_ROT":{
        "num":320,
        "description":""
    },
    "SC_ORG_SET_X_ROT":{
        "num":321,
        "description":""
    },
    "SC_ORG_SET_Y_ROT":{
        "num":322,
        "description":""
    },
    "SC_ORG_SET_Z_ROT":{
        "num":323,
        "description":""
    },
    "SET_SC_KOTEI_CAM_POS":{
        "num":324,
        "description":""
    },
    "SET_SC_KOTEI_CAM_T_POS":{
        "num":325,
        "description":""
    },
    "START_SC_WIPER":{
        "num":326,
        "description":""
    },
    "SUPER_DRIFT":{
        "num":327,
        "description":""
    },
    "CNG_TRAIN_NO_MAT_COL":{
        "num":328,
        "description":""
    },
    "ERR_CMD":{
        "num":329,
        "description":""
    },
    "K_HN":{
        "num":330,
        "description":""
    },
    "TO_TRACK_RAIL":{
        "num":331,
        "description":""
    },
    "IS_NO_DRAMA":{
        "num":332,
        "description":""
    },
    "CNG_TRAIN_NO_MAT_RGBA":{
        "num":333,
        "description":""
    },
    "SHOW_RECORD":{
        "num":334,
        "description":""
    },
    "WAIT_RECORD_END":{
        "num":335,
        "description":""
    },
    "IB_LI_SET_UPDATE_FLG":{
        "num":336,
        "description":""
    },
    "PTCL_SCALL":{
        "num":337,
        "description":""
    },
    "PTCL_COLOR":{
        "num":338,
        "description":""
    },
    "PTCL_ALPHA":{
        "num":339,
        "description":""
    },
    "PTCL_DRAWTYPE":{
        "num":340,
        "description":""
    },
    "PTCL_ANGLE":{
        "num":341,
        "description":""
    },
    "PTCL_RAND_ANGLE":{
        "num":342,
        "description":""
    },
    "PTCL_RAND_COLOR":{
        "num":343,
        "description":""
    },
    "PTCL_RAND_ALPHA":{
        "num":344,
        "description":""
    },
    "PTCL_RAND_SCALL":{
        "num":345,
        "description":""
    },
    "IB_ADD_PTCL":{
        "num":346,
        "description":""
    },
    "PTCL_RAND_TONE_COLOR":{
        "num":347,
        "description":""
    },
    "IS_ALPHA_END":{
        "num":348,
        "description":""
    },
    "PTCL_L_POS":{
        "num":349,
        "description":""
    },
    "PTCL_RAND_L_POS":{
        "num":350,
        "description":""
    },
    "CREATE_MAT_COLOR_R_INTERLIST":{
        "num":351,
        "description":""
    },
    "CREATE_MAT_EMISSIVE_R_INTERLIST":{
        "num":352,
        "description":""
    },
    "SET_MAT_COLOR_R":{
        "num":353,
        "description":""
    },
    "SET_MAT_COLOR_G":{
        "num":354,
        "description":""
    },
    "SET_MAT_COLOR_B":{
        "num":355,
        "description":""
    },
    "SET_MAT_COLOR_LOOP":{
        "num":356,
        "description":""
    },
    "SET_MAT_EMISSIVE_R":{
        "num":357,
        "description":""
    },
    "SET_MAT_EMISSIVE_G":{
        "num":358,
        "description":""
    },
    "SET_MAT_EMISSIVE_B":{
        "num":359,
        "description":""
    },
    "SET_MAT_EMISSIVE_LOOP":{
        "num":360,
        "description":""
    },
    "CREATE_MAT_COLOR_G_INTERLIST":{
        "num":361,
        "description":""
    },
    "CREATE_MAT_EMISSIVE_G_INTERLIST":{
        "num":362,
        "description":""
    },
    "CREATE_MAT_COLOR_B_INTERLIST":{
        "num":363,
        "description":""
    },
    "CREATE_MAT_EMISSIVE_B_INTERLIST":{
        "num":364,
        "description":""
    },
    "CREATE_UV_MOVE_Y":{
        "num":365,
        "description":""
    },
    "SET_UV_MOVE_Y":{
        "num":366,
        "description":""
    },
    "SET_UV_LOOP_Y":{
        "num":367,
        "description":""
    },
    "INDEX_RAND_ROT_X":{
        "num":368,
        "description":""
    },
    "INDEX_RAND_ROT_Y":{
        "num":369,
        "description":""
    },
    "INDEX_RAND_ROT_Z":{
        "num":370,
        "description":""
    },
    "INDEX_RAND_POS_X":{
        "num":371,
        "description":""
    },
    "INDEX_RAND_POS_Y":{
        "num":372,
        "description":""
    },
    "INDEX_RAND_POS_Z":{
        "num":373,
        "description":""
    },
    "RAND_SHOW_MESH":{
        "num":374,
        "description":""
    },
    "INDEX_RAND_SCALL":{
        "num":375,
        "description":""
    },
    "ADD_CHILD_OBJ":{
        "num":376,
        "description":""
    },
    "ADD_OBJ_INDEX":{
        "num":377,
        "description":""
    },
    "GAS_TARBIN":{
        "num":378,
        "description":""
    },
    "ENGINE_START":{
        "num":379,
        "description":""
    },
    "CHANGE_CHILDOBJ_ANIME":{
        "num":380,
        "description":""
    },
    "IB_SET_W_MT":{
        "num":381,
        "description":""
    },
    "CHK_OBJ_PARAM":{
        "num":382,
        "description":""
    },
    "SET_OBJ_PARAM":{
        "num":383,
        "description":""
    },
    "INDEX_DIR_CAM":{
        "num":384,
        "description":""
    },
    "CNG_MT_LIGHT":{
        "num":385,
        "description":""
    },
    "ADD_OBJ_INDEX2":{
        "num":386,
        "description":""
    },
    "CNG_MT_ALPHA":{
        "num":387,
        "description":""
    },
    "CREATE_MAT_ALPHA_INTERLIST":{
        "num":388,
        "description":""
    },
    "SET_MAT_ALPHA":{
        "num":389,
        "description":""
    },
    "RESTART_MESH_LIST":{
        "num":390,
        "description":""
    },
    "RAIL_ANIME_CHANGE":{
        "num":391,
        "description":""
    },
    "STOP_COMIC_SE_ALL":{
        "num":392,
        "description":""
    },
    "HURIKO":{
        "num":393,
        "description":""
    },
    "FTV_PLAY_AND_PREV":{
        "num":394,
        "description":""
    },
    "FTV_END_INHERIT":{
        "num":395,
        "description":""
    },
    "STATION_NAME_PRIORITY":{
        "num":396,
        "description":""
    },
    "ALL_FIT":{
        "num":397,
        "description":""
    },
    "SWAP_TX":{
        "num":398,
        "description":""
    },
    "CNG_TX":{
        "num":399,
        "description":""
    },
    "CHK_CAUSE":{
        "num":400,
        "description":""
    },
    "CNG_ANIME":{
        "num":401,
        "description":""
    },
    "CHK_OUHUKU":{
        "num":402,
        "description":""
    },
    "SET_TRAIN_PTCL_AREA":{
        "num":403,
        "description":""
    },
    "WAIT_DOSAN_LENGTH":{
        "num":404,
        "description":""
    },
    "END_DOSAN_LENGTH":{
        "num":405,
        "description":""
    },
    "DOSANSEN":{
        "num":406,
        "description":""
    },
    "MESH_INDEX_SE_UV_ANIME_FLG":{
        "num":407,
        "description":""
    },
    "WEATHER":{
        "num":408,
        "description":""
    },
    "TRAIN_DIR":{
        "num":409,
        "description":""
    },
    "IS_USE_CHAR":{
        "num":410,
        "description":""
    },
    "QUICK_SAVE_EVENT":{
        "num":411,
        "description":""
    },
    "NONE_GOAL":{
        "num":412,
        "description":""
    },
    "ENGINE_STOP":{
        "num":413,
        "description":""
    },
    "IS_BTL_MODE":{
        "num":414,
        "description":""
    },
    "IS_FREE_MODE":{
        "num":415,
        "description":""
    },
    "FIRST_OBJ_SET_ANIME_SCENE":{
        "num":416,
        "description":""
    },
    "G_HIDE_MESH":{
        "num":417,
        "description":""
    },
    "G_SHOW_MESH":{
        "num":418,
        "description":""
    },
    "STOP_WIPER":{
        "num":419,
        "description":""
    },
    "TRAIN_ANIME_CHANGE":{
        "num":420,
        "description":""
    },
    "MESH_INDEX_UV_RESTRT":{
        "num":421,
        "description":""
    },
    "SET_COMIC_COLOR":{
        "num":422,
        "description":""
    },
    "CHK_OUTRUN_CNT":{
        "num":423,
        "description":""
    },
    "CHK_D_AND_NOTCH":{
        "num":424,
        "description":""
    },
    "ADD_CPU_LEN_OUTRUN":{
        "num":425,
        "description":""
    },
    "ADD_CPU_SPEED_D_AND_NOTCH":{
        "num":426,
        "description":""
    },
    "CHK_HIT_CNT":{
        "num":427,
        "description":""
    },
    "TOP_SPEED_HOSYO":{
        "num":428,
        "description":""
    },
    "SET_ROOT_BLOCK":{
        "num":429,
        "description":""
    },
    "RIFT":{
        "num":430,
        "description":""
    },
    "COLLISION":{
        "num":431,
        "description":""
    },
    "DIR_VIEW_CHANGE":{
        "num":432,
        "description":""
    },
    "CHK_RAIL_NO":{
        "num":433,
        "description":""
    },
    "TRACK_CHANGE":{
        "num":434,
        "description":""
    },
    "CHK_LENGTH_DIR":{
        "num":435,
        "description":""
    },
    "CHK_POS_DIR":{
        "num":436,
        "description":""
    },
    "TRUE_CLASH":{
        "num":437,
        "description":""
    },
    "KATARIN_RUN":{
        "num":438,
        "description":""
    },
    "DRAW_UI":{
        "num":439,
        "description":""
    },
    "STOP_SCRIPT_BGM":{
        "num":440,
        "description":""
    },
    "SET_STATION_NO":{
        "num":441,
        "description":""
    },
    "SET_CPU_BREAKE":{
        "num":442,
        "description":""
    },
    "AMB_ANIME":{
        "num":443,
        "description":""
    },
    "ONE_DRIFT_FALSE":{
        "num":444,
        "description":""
    },
    "L_One_Drift":{
        "num":445,
        "description":""
    },
    "R_One_Drift":{
        "num":446,
        "description":""
    },
    "Ret_One_Drift":{
        "num":447,
        "description":""
    },
    "FRONT_JUMP":{
        "num":448,
        "description":""
    },
    "REAR_JUMP":{
        "num":449,
        "description":""
    },
    "FRONT_MOVE_X":{
        "num":450,
        "description":""
    },
    "TRACK_MOVE":{
        "num":451,
        "description":""
    },
    "TRAIN_JUMP":{
        "num":452,
        "description":""
    },
    "SET_LIGHT":{
        "num":453,
        "description":""
    },
    "SET_COL_KASENCHU":{
        "num":454,
        "description":""
    },
    "SET_KAISO":{
        "num":455,
        "description":""
    },
    "SET_FOR":{
        "num":456,
        "description":""
    },
    "CHK_TRAIN_COL":{
        "num":457,
        "description":""
    },
    "VOL_SCRIPT_BGM":{
        "num":458,
        "description":""
    },
    "IF_NOTCH":{
        "num":459,
        "description":""
    },
    "SET_BRIND_SW":{
        "num":460,
        "description":""
    },
    "SET_MIKOSHI":{
        "num":461,
        "description":""
    },
    "ADD_FIRE":{
        "num":462,
        "description":""
    },
    "BREAKE_OR_HIT":{
        "num":463,
        "description":""
    },
    "OUTRUN":{
        "num":464,
        "description":""
    },
    "SOFT_ATK":{
        "num":465,
        "description":""
    },
    "RAIL_STOP":{
        "num":466,
        "description":""
    },
    "CHANGE_OUHUKU_LINE":{
        "num":467,
        "description":""
    },
    "BRIND_ATK":{
        "num":468,
        "description":""
    },
    "OPEN_POS_DLG":{
        "num":469,
        "description":""
    },
    "PLAY_STAGEBGM_BLOCK":{
        "num":470,
        "description":""
    },
    "SET_BTL_POINT":{
        "num":471,
        "description":""
    },
    "CAM_TRAIN":{
        "num":472,
        "description":""
    },
    "PLAY_SCRIPT_BGM":{
        "num":473,
        "description":""
    },
    "CNG_FOR":{
        "num":474,
        "description":""
    },
    "SET_RAILBLOCK_CHECKER":{
        "num":475,
        "description":""
    },
    "RAIN_SE":{
        "num":476,
        "description":""
    },
    "TRAIN_STOP":{
        "num":477,
        "description":""
    },
    "KOTEICAM_BLEND":{
        "num":478,
        "description":""
    },
    "SCRIPT_RAIN":{
        "num":479,
        "description":""
    },
    "LINE_CHANGE":{
        "num":480,
        "description":""
    },
    "WAIT_RAIL_MORE_ONLY":{
        "num":481,
        "description":""
    },
    "SET_SE_VOL":{
        "num":482,
        "description":""
    },
    "CAM_TARGET_TRACK":{
        "num":483,
        "description":""
    },
    "DECAL_D37":{
        "num":484,
        "description":""
    },
    "DECAL_D39":{
        "num":485,
        "description":""
    },
    "DECAL_SMOKE":{
        "num":486,
        "description":""
    },
    "RAIL_PRIORITY":{
        "num":487,
        "description":""
    },
    "GET_KEY":{
        "num":488,
        "description":""
    },
    "SHOW_LIGHT":{
        "num":489,
        "description":""
    },
    "SHOW_IN_LIGHT":{
        "num":490,
        "description":""
    },
    "FOG_POW":{
        "num":491,
        "description":""
    },
    "STORY_WIN":{
        "num":492,
        "description":""
    },
    "RAIN_PARTICLE":{
        "num":493,
        "description":""
    },
    "D39_FIRE":{
        "num":494,
        "description":""
    },
    "SET_CPU_SPEED":{
        "num":495,
        "description":""
    },
    "BODY_AUDIO_PLAY":{
        "num":496,
        "description":""
    },
    "BODY_AUDIO_STOP":{
        "num":497,
        "description":""
    },
    "CNG_FADE_SPRITE":{
        "num":498,
        "description":""
    },
    "RAIL_DRIFT_CHK":{
        "num":499,
        "description":""
    },
    "INQ_WAIT":{
        "num":500,
        "description":""
    },
    "CNG_SCCAM_TRAIN":{
        "num":501,
        "description":""
    },
    "STOP_TRAIN_SE":{
        "num":502,
        "description":""
    },
    "PLAY_SCRIPT_BGM_TIME":{
        "num":503,
        "description":""
    },
    "CNG_BODY_COLOR":{
        "num":504,
        "description":""
    },
    "LOAD_TRAIN":{
        "num":505,
        "description":""
    },
    "SHOW_BLOCK":{
        "num":506,
        "description":""
    },
    "UPDATE_LIGHT_FRARE":{
        "num":507,
        "description":""
    },
    "WAIT_RAIL_MORE_GOTO":{
        "num":508,
        "description":""
    },
    "CREATE_AURA":{
        "num":509,
        "description":""
    },
    "AURA_ALPHA":{
        "num":510,
        "description":""
    },
    "SET_LV_JUMP":{
        "num":511,
        "description":""
    },
    "CREATE_EFFECT_CAM":{
        "num":512,
        "description":""
    },
    "TO_EFFECT_CAM":{
        "num":513,
        "description":""
    },
    "EFFECT_CAM_POW":{
        "num":514,
        "description":""
    },
    "EFFECT_CAM_COLOR":{
        "num":515,
        "description":""
    },
    "EFFECT_CAM_ALPHA":{
        "num":516,
        "description":""
    },
    "HIDE_LIGHT":{
        "num":517,
        "description":""
    },
    "USE_EFFECT_CAM":{
        "num":518,
        "description":""
    },
    "USE_EFFECT_CAM_RGB":{
        "num":519,
        "description":""
    },
    "EFFECT_CAM_RGB":{
        "num":520,
        "description":""
    },
    "COPY_TRAIN_POS":{
        "num":521,
        "description":""
    },
    "COL_SET":{
        "num":522,
        "description":""
    },
    "CNG_CPU_TRAIN":{
        "num":523,
        "description":""
    },
    "BTN_GOTO":{
        "num":524,
        "description":""
    },
    "NO_TIMESCALE_KOMA":{
        "num":525,
        "description":""
    },
    "EFFCAM_NOIZE":{
        "num":526,
        "description":""
    },
    "EFFCAM_GRI":{
        "num":527,
        "description":""
    },
    "EFFCAM_BLOCKNOISE":{
        "num":528,
        "description":""
    },
    "CREATE_TQ5000_FLAGMENT":{
        "num":529,
        "description":""
    },
    "USE_TQ5000_FLAGMENT":{
        "num":530,
        "description":""
    },
    "TQ5000_FLAGPOS":{
        "num":531,
        "description":""
    },
    "HUMIKIRI_VOL":{
        "num":532,
        "description":""
    },
    "TO_EFFECT_CAM_BODY":{
        "num":533,
        "description":""
    },
    "TO_NORM_CAM":{
        "num":534,
        "description":""
    },
    "TO_920":{
        "num":535,
        "description":""
    },
    "NO_TIMESCALE_FVT":{
        "num":536,
        "description":""
    },
    "CNG_TARGET_BODY":{
        "num":537,
        "description":""
    },
    "SC_ADD_POINT":{
        "num":538,
        "description":""
    },
    "CHK_SC_POINT":{
        "num":539,
        "description":""
    },
    "KAISO_TO_DUEL":{
        "num":540,
        "description":""
    },
    "SHOW_ST":{
        "num":541,
        "description":""
    },
    "ORG_UPDATE":{
        "num":542,
        "description":""
    },
    "SET_RAILBLOCK_POS":{
        "num":543,
        "description":""
    },
    "SET_LIGHT_OVER":{
        "num":544,
        "description":""
    },
    "CREATE_STAFFROLL":{
        "num":545,
        "description":""
    },
    "STAFFROLL_START":{
        "num":546,
        "description":""
    },
    "WAIT_STAFFROLL":{
        "num":547,
        "description":""
    },
    "SC_OUTRUN":{
        "num":548,
        "description":""
    },
    "CREATE_TAKMIS":{
        "num":549,
        "description":""
    },
    "SET_TAKMIS_POS":{
        "num":550,
        "description":""
    },
    "SET_TAKMIS_ALPHA":{
        "num":551,
        "description":""
    },
    "FRONT_DOOR":{
        "num":552,
        "description":""
    },
    "SET_KOMA_DEPTH":{
        "num":553,
        "description":""
    },
    "D37_FIRE":{
        "num":554,
        "description":""
    },
    "AMB_HIT_WAIT":{
        "num":555,
        "description":""
    },
    "ShowRecord":{
        "num":556,
        "description":""
    },
    "FIT_PER":{
        "num":557,
        "description":""
    },
    "CREATE_COMIC_PC":{
        "num":558,
        "description":""
    },
    "SET_COMIC_PC":{
        "num":559,
        "description":""
    },
    "PAUSE_STAGE_BGM":{
        "num":560,
        "description":""
    },
    "SET_KAKAPO":{
        "num":561,
        "description":""
    },
    "KOMA_KAKAPO":{
        "num":562,
        "description":""
    },
    "START_TARBINE":{
        "num":563,
        "description":""
    },
    "END_TARBINE":{
        "num":564,
        "description":""
    },
    "TARBINE_FTV_START":{
        "num":565,
        "description":""
    },
    "TARBINE_FTV_END":{
        "num":566,
        "description":""
    },
    "STORY_ENGINE":{
        "num":567,
        "description":""
    },
    "RAND_GOTO":{
        "num":568,
        "description":""
    },
    "KQ_SOUND":{
        "num":569,
        "description":""
    },
    "STORY_GOTO":{
        "num":570,
        "description":""
    },
    "PLAY223HONE":{
        "num":571,
        "description":""
    },
    "RB26":{
        "num":572,
        "description":""
    },
    "PLAYORGSE":{
        "num":573,
        "description":""
    },
    "H2300_GOAL":{
        "num":574,
        "description":""
    },
    "SCRIPT_CMD_MAX":{
        "num":575,
        "description":""
    },
};